### ISSUE TITLE
On Linux Arm64

### ISSUE THREAD

**Issue by Joleme** [zhongzf/Xamarin.Forms.Platform.Avalonia#12]
Embedded Linux by YoctoProject
Distro : Sumo
Display : xWayland
.Net core 3.1

When starting the demo, I got partial screen renderer and after a wild, a Stackoverflow. And as you can seen on the picture, when trying to render, the process use more than 100%.

On windows everything work just fine.

![IMG_20200320_140436](https://user-images.githubusercontent.com/13201257/77193930-65564980-6ab5-11ea-9284-2bb634c09863.jpg)

**Comment by zhongzf** [comment]
did you try pure Avalonia application on it? does it work? I tested with Ubuntu on x64, it works, not sure about ARM64.
try this first:
https://github.com/AvaloniaUI/Avalonia

**Comment by Joleme** [comment]
Pure Avalonia : Yes work great on my board iMX8-Nano
Linux x64 : Yes work great too on ubuntu 18....

the application seems bugging in this method :
class : CommandBar
protected override void OnTemplateApplied(TemplateAppliedEventArgs e)
{
base.OnTemplateApplied(e);

_moreButton = e.NameScope.Find<Button>("MoreButton");
_primaryItemsControl = e.NameScope.Find<ItemsControl>("PrimaryItemsControl");
}

After that, nothing append, except the stackoverflow.

thank you for your time


________________________________

**Comment by Joleme** [comment]
This wasn't code bugs.  My distribution missed too much components.
